---
abstract: 'connection wrapper for im.kayac.com'
author:
  - hisaichi5518
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::ImKayac
name: WWW-ImKayac
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  AnyEvent::HTTP: 0
  Carp: 0
  Digest::SHA1: 0
  Furl: 0
  HTTP::Request::Common: 0
  JSON::XS: 0
  Mouse: 0.7
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
